#INT 354


##Project:- Predicting Financial Market Volatility using News Sentiment


In [ ]:
## https://www.kaggle.com/datasets/aaron7sun/stocknews link of news dataset
import pandas as pd
import numpy as np


In [ ]:
df = pd.read_csv("/content/News.csv",encoding="ISO-8859-1") # this is why we using encodeing bcoz of (UTF-8 codec can't decode byte 0xa3 in position 7092: invalid start byte)

In [ ]:
df.head()

Date  Label                                               Top1  \
0  2000-01-03      0  A 'hindrance to operations': extracts from the...   
1  2000-01-04      0                                          Scorecard   
2  2000-01-05      0                  Coventry caught on counter by Flo   
3  2000-01-06      1                      Pilgrim knows how to progress   
4  2000-01-07      1                               Hitches and Horlocks   

                                 Top2  \
0                           Scorecard   
1                 The best lake scene   
2  United's rivals on the road to Rio   
3                 Thatcher facing ban   
4      Beckham off but United survive   

                                            Top3  \
0                Hughes' instant hit buoys Blues   
1                  Leader: German sleaze inquiry   
2  Thatcher issues defence before trial by video   
3        McIlroy calls for Irish fighting spirit   
4                        Breast cancer screening   

                                            Top4  \
0       Jack gets his skates on at ice-cold Alex   
1                                  Cheerio, boyo   
2  Police help Smith lay down the law at Everton   
3                Leicester bin stadium blueprint   
4                                    Alan Parker   

                                          Top5  \
0       Chaos as Maracana builds up for United   
1                     The main recommendations   
2  Tale of Trautmann bears two more retellings   
3               United braced for Mexican wave   
4      Guardian readers: are you all whingers?   

                                                Top6  \
0  Depleted Leicester prevail as Elliott spoils E...   
1                             Has Cubie killed fees?   
2                                England on the rack   
3  Auntie back in fashion, even if the dress look...   
4                                   Hollywood Beyond   

                                              Top7  \
0                 Hungry Spurs sense rich pickings   
1                           Has Cubie killed fees?   
2  Pakistan retaliate with call for video of Walsh   
3                    Shoaib appeal goes to the top   
4                               Ashes and diamonds   

                                                Top8  ...  \
0                  Gunners so wide of an easy target  ...   
1                             Has Cubie killed fees?  ...   
2               Cullinan continues his Cape monopoly  ...   
3  Hussain hurt by 'shambles' but lays blame on e...  ...   
4                   Whingers - a formidable minority  ...   

                                               Top16  \
0           Flintoff injury piles on woe for England   
1                               On the critical list   
2                        South Melbourne (Australia)   
3  Putin admits Yeltsin quit to give him a head s...   
4                             Most everywhere:  UDIs   

                                               Top17  \
0  Hunters threaten Jospin with new battle of the...   
1                          The timing of their lives   
2                                    Necaxa (Mexico)   
3         BBC worst hit as digital TV begins to bite   
4                       Most wanted:  Chloe lunettes   

                                            Top18  \
0             Kohl's successor drawn into scandal   
1                                     Dear doctor   
2                             Real Madrid (Spain)   
3                     How much can you pay for...   
4  Return of the cane 'completely off the agenda'   

                                               Top19  \
0               The difference between men and women   
1  Irish court halts IRA man's extradition to Nor...   
2                          Raja Casablanca (Morocco)   
3                                 Christmas glitches   
4                   From Sleepy Hollow to Greeneland   

                         

In [ ]:
df.tail()

Date  Label                                               Top1  \
4096  2016-06-27      0  Barclays and RBS shares suspended from trading...   
4097  2016-06-28      1  2,500 Scientists To Australia: If You Want To ...   
4098  2016-06-29      1                   Explosion At Airport In Istanbul   
4099  2016-06-30      1  Jamaica proposes marijuana dispensers for tour...   
4100  2016-07-01      1  A 117-year-old woman in Mexico City finally re...   

                                                   Top2  \
4096  Pope says Church should ask forgiveness from g...   
4097  The personal details of 112,000 French police ...   
4098  Yemeni former president: Terrorism is the offs...   
4099  Stephen Hawking says pollution and 'stupidity'...   
4100   IMF chief backs Athens as permanent Olympic host   

                                                   Top3  \
4096  Poland 'shocked' by xenophobic abuse of Poles ...   
4097  S&amp;P cuts United Kingdom sovereign credit r...   
4098  UK must accept freedom of movement to access E...   
4099  Boris Johnson says he will not run for Tory pa...   
4100  The president of France says if Brexit won, so...   

                                                   Top4  \
4096  There will be no second referendum, cabinet ag...   
4097                Huge helium deposit found in Africa   
4098  Devastated: scientists too late to captive bre...   
4099  Six gay men in Ivory Coast were abused and for...   
4100  British Man Who Must Give Police 24 Hours' Not...   

                                                   Top5  \
4096      Scotland welcome to join EU, Merkel ally says   
4097  CEO of the South African state broadcaster qui...   
4098  British Labor Party leader Jeremy Corbyn loses...   
4099  Switzerland denies citizenship to Muslim immig...   
4100  100+ Nobel laureates urge Greenpeace to stop o...   

                                                   Top6  \
4096  Sterling dips below Friday's 31-year low amid ...   
4097  Brexit cost investors $2 trillion, the worst o...   
4098  A Muslim Shop in the UK Was Just Firebombed Wh...   
4099  Palestinian terrorist stabs israeli teen girl ...   
4100  Brazil: Huge spike in number of police killing...   

                                                   Top7  \
4096  No negative news about South African President...   
4097  Hong Kong democracy activists call for return ...   
4098  Mexican Authorities Sexually Torture Women in ...   
4099  Puerto Rico will default on $1 billion of debt...   
4100  Austria's highest court annuls presidential el...   

                                                   Top8  ...  \
4096  Surge in Hate Crimes in the U.K. Following U.K...  ...   
4097  Brexit: Iceland president says UK can join 'tr...  ...   
4098            UK shares and pound continue to recover  ...   
4099  Republic of Ireland fans to be awarded medal f...  ...   
4100  Facebook wins privacy case, can track any Belg...  ...   

                                                  Top16  \
4096  German lawyers to probe Erdogan over alleged w...   
4097  US, Canada and Mexico pledge 50% of power from...   
4098  Escape Tunnel, Dug by Hand, Is Found at Holoca...   
4099  Googles free wifi at Indian railway stations i...   
4100  The United States has placed Myanmar, Uzbekist...   

                                                  Top17  \
4096  Boris Johnson says the UK will continue to "in...   
4097  There is increasing evidence that Australia is...   
4098  The land under Beijing is sinking by as much a...   
4099  Mounting evidence suggests 'hobbits' were wipe...   
4100  S&amp;P revises European Union credit rating t...   

                                                  Top18  \
4096  Richard Branson is calling on the UK governmen...   
4097  Richard Branson, the founder of Virgin Group, ...   
4098  Car bomb and Anti-Islamic attack on Mosque in ...   
4099  The men who carried out Tuesday's terror attac...   
4100  India gets $1 bil

In [ ]:
df.shape

(4101, 27)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4101 entries, 0 to 4100
Data columns (total 27 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Date    4101 non-null   object
 1   Label   4101 non-null   int64 
 2   Top1    4101 non-null   object
 3   Top2    4101 non-null   object
 4   Top3    4101 non-null   object
 5   Top4    4101 non-null   object
 6   Top5    4101 non-null   object
 7   Top6    4101 non-null   object
 8   Top7    4101 non-null   object
 9   Top8    4101 non-null   object
 10  Top9    4101 non-null   object
 11  Top10   4101 non-null   object
 12  Top11   4101 non-null   object
 13  Top12   4101 non-null   object
 14  Top13   4101 non-null   object
 15  Top14   4101 non-null   object
 16  Top15   4101 non-null   object
 17  Top16   4101 non-null   object
 18  Top17   4101 non-null   object
 19  Top18   4101 non-null   object
 20  Top19   4101 non-null   object
 21  Top20   4101 non-null   object
 22  Top21   4101 non-null   

In [ ]:
df.isnull().sum()

Date     0
Label    0
Top1     0
Top2     0
Top3     0
Top4     0
Top5     0
Top6     0
Top7     0
Top8     0
Top9     0
Top10    0
Top11    0
Top12    0
Top13    0
Top14    0
Top15    0
Top16    0
Top17    0
Top18    0
Top19    0
Top20    0
Top21    0
Top22    0
Top23    1
Top24    3
Top25    3
dtype: int64

In [ ]:
null_values_in_df = df[df.isnull().any(axis=1)]

In [ ]:
## About Dataset here we are having 27 coloumns and 4101 rows
## Out of 27  -> 25 are for my top news ,1 is representing the date ,1 is representing on that day my graph was up or down
## we are having news of 16 years approx from 2000-01-03 till 2016-07-01

In [ ]:
train = df[df["Date"]<'20150101']
test = df[df["Date"]>'20141231']

In [ ]:
test.shape

(378, 27)

In [ ]:
## Now we will Do preprocessing and Training
## step 1: remove all the puchuations and will convert to lower case
## step 2: now combine all the news
## step 3: convert  news to vector Techniques to be use is (CountVectorize(This is feature extraction Techniques))
## step 4: use ML algorithmns to predict  Like(Naive Bayes, RandomForest, KNNClasiifier)
## step 5: To check the performance we will different types of metrices

In [ ]:
## step1
## for train
data_train = train.iloc[:,2:]
data_train.replace("[^a-zA-Z]"," ",regex=True, inplace=True) #regex is true bocz we want to repalce except some data
## for test
data_test = test.iloc[:,2:]
data_test.replace("[^a-zA-Z]"," ",regex=True, inplace=True)

In [ ]:
## step 2:
## for train
for i in data_train.columns:
  data_train[i] = data_train[i].str.lower()

## for test
for i in data_test.columns:
  data_test[i] = data_test[i].str.lower()

In [ ]:
## step 3

## For Train
combine_train = []

for i in range(0,data_train.shape[0]):
  combine_train.append(' '.join(str(x) for x in data_train.iloc[i,:]))

## For Test
combine_test = []

for i in range(0,data_test.shape[0]):
  combine_test.append(' '.join(str(x) for x in data_test.iloc[i,:]))


In [ ]:
combine_train[0]

'a  hindrance to operations   extracts from the leaked reports scorecard hughes  instant hit buoys blues jack gets his skates on at ice cold alex chaos as maracana builds up for united depleted leicester prevail as elliott spoils everton s party hungry spurs sense rich pickings gunners so wide of an easy target derby raise a glass to strupar s debut double southgate strikes  leeds pay the penalty hammers hand robson a youthful lesson saints party like it s      wear wolves have turned into lambs stump mike catches testy gough s taunt langer escapes to hit     flintoff injury piles on woe for england hunters threaten jospin with new battle of the somme kohl s successor drawn into scandal the difference between men and women sara denver  nurse turned solicitor diana s landmine crusade put tories in a panic yeltsin s resignation caught opposition flat footed russian roulette sold out recovering a title'

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

## For Train
countvec = CountVectorizer(ngram_range=(2,2))
train_data=countvec.fit_transform(combine_train)
test_data = countvec.transform(combine_test)

In [ ]:
# For RandomForest
model_1 = RandomForestClassifier(n_estimators=150,criterion="entropy")
model_1.fit(train_data,train["Label"])


RandomForestClassifier(criterion='entropy', n_estimators=150)

In [ ]:
x_pred = model_1.predict(test_data)
print("This is for RandomForest")
print(confusion_matrix(x_pred,test["Label"]))
print(accuracy_score(x_pred,test["Label"])*100)
print(classification_report(x_pred,test["Label"]))

This is for RandomForest
[[142   9]
 [ 44 183]]
0.37566137566137564
              precision    recall  f1-score   support

           0       0.76      0.94      0.84       151
           1       0.95      0.81      0.87       227

    accuracy                           0.86       378
   macro avg       0.86      0.87      0.86       378
weighted avg       0.88      0.86      0.86       378



In [ ]:
## For Naivebayes

model_2 = MultinomialNB()
model_2.fit(train_data,train["Label"])

x_pred = model_2.predict(test_data)
print("This is for NaiveBayes")
print(confusion_matrix(x_pred,test["Label"]))
print(accuracy_score(x_pred,test["Label"])*100)
print(classification_report(x_pred,test["Label"]))


This is for RandomForest
[[138  10]
 [ 48 182]]
84.65608465608466
              precision    recall  f1-score   support

           0       0.74      0.93      0.83       148
           1       0.95      0.79      0.86       230

    accuracy                           0.85       378
   macro avg       0.84      0.86      0.84       378
weighted avg       0.87      0.85      0.85       378



In [ ]:
## For KNN classifier

model_3 = KNeighborsClassifier(n_neighbors=5)
model_3.fit(train_data,train["Label"])

x_pred = model_3.predict(test_data)
print("This is for KNNClassifier")
print(confusion_matrix(x_pred,test["Label"]))
print(accuracy_score(x_pred,test["Label"])*100)
print(classification_report(x_pred,test["Label"]))

This is for KNNClassifier
[[ 17   0]
 [169 192]]
55.29100529100529
              precision    recall  f1-score   support

           0       0.09      1.00      0.17        17
           1       1.00      0.53      0.69       361

    accuracy                           0.55       378
   macro avg       0.55      0.77      0.43       378
weighted avg       0.96      0.55      0.67       378



In [ ]:
## For DecisionTreeClassifier
from sklearn.tree import DecisionTreeClassifier
model_4 = DecisionTreeClassifier()
model_4.fit(train_data,train["Label"])

x_pred = model_4.predict(test_data)
print("This is for KNNClassifier")
print(confusion_matrix(x_pred,test["Label"]))
print(accuracy_score(x_pred,test["Label"])*100)
print(classification_report(x_pred,test["Label"]))

This is for KNNClassifier
[[158  34]
 [ 28 158]]
83.5978835978836
              precision    recall  f1-score   support

           0       0.85      0.82      0.84       192
           1       0.82      0.85      0.84       186

    accuracy                           0.84       378
   macro avg       0.84      0.84      0.84       378
weighted avg       0.84      0.84      0.84       378

